### ISSUE TITLE
core about watch

### ISSUE THREAD

**Issue by lyhuzi** [nokia/etcd-cpp-apiv3#7] opened 2017-06-19 10:03 UTC
the core general in v3/src/AsyncWatchAction.cpp
stream->Write(watch_req, (void*)"write");

**Comment by zhangwuliang** [comment] 2017-06-21 09:27
I have also encountered this problem, Have you solved it? How to solve?

**Comment by mauiarches** [comment] 2017-06-21 10:11
Hello,

What assertion did you got? I also encountered an assertion in watch in gRPC. However, when I used gRPC version VERSION_GRPC=1.2.0 the assertion went away. I also saw this issue in etcd github but i have to find the link first.

**Comment by zhangwuliang** [comment] 2017-06-21 10:24
assertion failed: GRPC_CALL_OK == grpc_call_start_batch(call->call(), cops, nops, ops, nullptr)

**Comment by mauiarches** [comment] 2017-06-21 10:28
Hi,
Yes when i use this grpc version assertion is gone.

**Comment by zhangwuliang** [comment] 2017-06-21 10:29
@mauiarches  watcher can work?  I will have a try, thx!

**Comment by mauiarches** [comment] 2017-06-21 11:26
Hi,

There still problem with watcher regarding the tags. Have to fix this in the code.
However using the grpc 1.2.0 assertion is gone.

**Comment by zhangwuliang** [comment] 2017-06-22 01:37
@mauiarches Have you solved it?  I'm still troubled by this problem

**Comment by zhangwuliang** [comment] 2017-06-22 02:40
@mauiarches I used grpc 1.2.0, still can not slove this assertion

**Comment by zhangwuliang** [comment] 2017-06-23 10:01
@mauiarches Have you solved it?

**Comment by mauiarches** [comment] 2017-06-23 17:20
Hi,

Yes when i updated grpc version and compile again. No asserts

**Comment by zhangwuliang** [comment] 2017-06-26 02:46
@mauiarches  can watcher work well?

**Comment by mauiarches** [comment] 2017-06-26 18:42
Hi,

Tags needs to be updated in the watcher class. I have to ask ehrn it can be
committed

**Comment by zhangwuliang** [comment] 2017-06-27 03:06
@mauiarches  When will it be possible to fix this bug ? please let me know,  thanks

**Comment by danielzhanghl** [comment] 2017-07-07 07:32
hi, I get the same issue with grpc 1.4.1.
seems we've got the root cause(that's great), but not committed yet, could you paste the fix, we could build from source to have a early try.
thanks much.

**Comment by lyhuzi** [comment] 2017-07-13 08:07
出现这个问题的原因是这个库的代码问题，使用 grpc::ClientContext context; 建立stub后，context的生命周期必须要比stub要长。

**Comment by danielzhanghl** [comment] 2017-07-13 09:25
高人，何解？

**Comment by lyhuzi** [comment] 2017-07-13 11:34
28     template<typename T>static pplx::task<etcd::Response> create(std::shared_ptr<T> call) 
 29     {  
            // 下面这段代码，的call出去之后已经失效，call已经释放了，call中包含了grpc::ClientContext context等一系列信息，都不能访问了。所有会call
 30       return pplx::task<etcd::Response>([call]()                                          
 31       {                                                                                   
 32         etcd::Response resp;                                                              
 33                                                                                           
 34         call->waitForResponse();                                                          
 35                                                                                           
 36         auto v3resp = call->ParseResponse();                                              
 37                                                                                           
 38         resp = etcd::Response(v3resp);                                                    
 39                                                                                           
 40         return resp;                                                                      
 41       });                                                                                 
 42     }

**Comment by lyhuzi** [comment] 2017-07-13 11:48
这个库作者快一年都没维护了，并且代码这么大个bug都没有修，一看就没有自己测试，纯是写着玩的，大家不要用了，散了吧。在这里磨蹭花的时间就可以自己写一个了。

**Closed** 2017-07-17 10:11 UTC

**Comment by majianwei0705** [comment] 2021-01-05 11:31
any update about this ?
